# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Ekaterina-lazy/f0ac19d7b04ca2701327e55b3083e081/untitled0.ipynb
"""

print('\nДобро пожаловать! ' 'Создадим пароль?')
import string
import random

def generate_password(length):
  characters = string.ascii_letters + string.digits + string.punctuation
  password = ''.join(random.choice(characters) for _ in range(length))
  return password

password_length = int(input('Сколько символов в пароле?'))
password = generate_password(password_length)
print('Новый пароль:', password)