# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JJYvjG6_UqEw_s91K854IcsNUMXqpXu
"""

shopping_list = []

def remove_item():
    item = input("Введите товар для удаления: ")
    if item in shopping_list:
        shopping_list.remove(item)
        print(f"Товар '{item}' удален.")
    else:
        print(f"Товар '{item}' отсутствует в списке.")

def show_list(show_all=True):
    if not shopping_list:
        print("Список покупок пуст.")
        return
    if show_all:
        print("--- Ваш список покупок ---")
        for i, item in enumerate(shopping_list):
            print(f"{i+1}. {item}")

while True:
    print("\nВыберите действие:")
    print("1. Добавить товар")
    print("2. Удалить товар")
    print("3. Показать весь список")
    print("4. Закончить")

    choice = input("Введите номер действия: ")

    if choice == '1':
        add_item()
    elif choice == '2':
        remove_item()
    elif choice == '3':
        show_list(show_all=True)
    elif choice == '4':
        print("До свидания!")
        break
    else:
        print("Неверный выбор. Пожалуйста, попробуйте снова.")